import { Library } from "../types/models";
const date = "2026-09-01T12:00:00.000Z";
export const demoLibrary: Library = {
  version: 1,
  projects: [
    {
      id: "demo-remodelacion",
      name: "Proyecto Remodelación",
      description: "Renovación de espacios y seguimiento de obra.",
      createdAt: date,
      updatedAt: date,
      demo: true,
    },
    {
      id: "demo-electrica",
      name: "Instalación eléctrica",
      description: "Planos, reportes y evidencias de instalación.",
      createdAt: date,
      updatedAt: date,
      demo: true,
    },
    {
      id: "demo-oficina",
      name: "Proyecto oficina",
      description: "Un nuevo espacio para trabajar mejor.",
      createdAt: date,
      updatedAt: date,
      demo: true,
    },
  ],
  folders: [
    { id: "general", name: "General", protected: false },
    { id: "confidencial", name: "Confidencial", protected: true },
  ],
  files: [
    {
      id: "demo-contract",
      name: "Contrato de remodelación.pdf",
      uri: "",
      type: "contract",
      mimeType: "application/pdf",
      size: 245760,
      category: "contracts",
      company: "Constructora Horizonte · Demo",
      projectId: "demo-remodelacion",
      description: "Acuerdo de alcance, entregables y condiciones de la obra.",
      createdAt: date,
      protected: true,
      demo: true,
    },
    {
      id: "demo-report",
      name: "Reporte de avance.txt",
      uri: "",
      type: "document",
      size: 1024,
      category: "documents",
      projectId: "demo-electrica",
      description:
        "Seguimiento semanal de actividades y avances de instalación.",
      createdAt: date,
      protected: false,
      demo: true,
    },
    {
      id: "demo-evidence",
      name: "Visita a obra.jpg",
      uri: "",
      type: "image",
      mimeType: "image/jpeg",
      size: 1572864,
      category: "evidence",
      projectId: "demo-remodelacion",
      description: "Registro de la visita y revisión de avances en obra.",
      createdAt: date,
      protected: false,
      demo: true,
    },
  ],
};
